### PR TITLE
Fix secret loading

### PR DESCRIPTION
**Pull request by GabeLambda**
Convention in most apps using this library will be for config keys to be
camelCased. Other pieces of configuration software (e.g. ansible) may
store these values as snake_cased, and thus should be converted
appropriately when loaded here.

### CODE REVIEW

**Comment by mlcohen** [comment]
bump version

**Comment by GabeLambda** [comment]
@mlcohen I'll do that in the release PR.

**Comment by mlcohen** [comment]
Does the yarn.lock file need to be updated in this PR?

**Comment by GabeLambda** [comment]
It was broken as hell. Take a look at it.

**Pull request merged**
